deepseek-v3:
  api_key: "sk-b6609553e0c048869e088f4c7910b0c4"   # 替换为你的DeepSeek API Key
  base_url: "https://api.deepseek.com"  # DeepSeek API 地址
  # model: "deepseek-v3"              # 指定模型
  # temperature: 0.7                  # 可选参数
  # max_tokens: 2048                  # 可选参数

chatgpt-3.5:
  api_key: "sk-dqVmfYb7bqQ3b6Y4Bxh5LZTQSHKhDfzFGxIR8bWvWRNye7F9"
  base_url: "https://api.chatanywhere.tech/v1"