deepseek-v3.1:
  api_key: "sk-XWMACLkkgYedy2hfxcPw84L1pmbF6XyscAHE7QRspdozsON3"
  base_url: "https://api.chatanywhere.tech/v1"
  model: "deepseek-v3.1-250821"

gpt-3.5-turbo:
  api_key: "sk-XWMACLkkgYedy2hfxcPw84L1pmbF6XyscAHE7QRspdozsON3"
  base_url: "https://api.chatanywhere.tech/v1"
  model: "gpt-3.5-turbo"



